# Generated by Django 4.0.6 on 2022-07-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='referel_activated',
        ),
        migrations.RemoveField(
            model_name='account',
            name='referel_code',
        ),
    ]
