# Generated by Django 4.0.6 on 2022-07-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_is_superadmin_account_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_active',
            new_name='is_blocked',
        ),
    ]
