# Generated by Django 4.0.6 on 2022-07-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_is_active_account_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
