# Generated by Django 4.0.6 on 2022-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='india', max_length=200),
            preserve_default=False,
        ),
    ]
