# Generated by Django 4.0.6 on 2022-08-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='cochin', max_length=200),
            preserve_default=False,
        ),
    ]
